version: '3.8'

networks: 
  local:
    name: localhost
    external: true

volumes:
  postgres_data:
      name: postgresql-data
      driver: local

services:
  postgresql:
    container_name: postgresql-server
    image: postgres
    environment:
      POSTGRES_PASSWORD: "password"
    ports:
      - "15432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - local
      
  # pgadmin4:
  #   container_name: pgadmin4
  #   image: dpage/pgadmin4
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: "andremoriya@gmail.com"
  #     PGADMIN_DEFAULT_PASSWORD: "adminadmin"
  #   ports:
  #     - "16543:80"
  #   depends_on:
  #     - postgresql
  #   networks:
  #     - local