version: "3.8"

networks:
  local:
    name: localhost
    external: true

volumes:
  keycloak_data_latest:
    name: keycloak-latest
    driver: local

services:
  keycloak:
    container_name: keycloak-latest
    image: quay.io/keycloak/keycloak:latest
    command: ["-b", "0.0.0.0", "-bmanagement", "0.0.0.0"]
    volumes:
      - keycloak_data_latest:/opt/jboss/keycloak
    environment:
      PROXY_ADDRESS_FORWARDING: "true"
      DB_VENDOR: POSTGRES
      DB_ADDR: 172.18.0.2
      DB_DATABASE: keycloak12
      DB_USER: keycloak
      DB_SCHEMA: public
      DB_PASSWORD: keycloak
      #KEYCLOAK_USER: admin
      #KEYCLOAK_PASSWORD: admin
      #Uncomment the line below if you want to specify JDBC parameters. The parameter below is just an example, and it shouldn't be used in production without knowledge. It is highly recommended that you read the PostgreSQL JDBC driver documentation in order to use it.
      #JDBC_PARAMS: "ssl=true"
    ports:
      - 1100:8080
      - 1101:9990
    networks:
      - local
