version: '3.2'

volumes:
  keycloak_data:
      driver: local

services:
  keycloak:
      image: quay.io/keycloak/keycloak:latest
      volumes:
        - keycloak_data:/var/lib/keycloak
      environment:
        DB_VENDOR: MYSQL
        DB_DATABASE: keycloak
        DB_USER: root
        DB_PASSWORD: root
        KEYCLOAK_USER: admin
        KEYCLOAK_PASSWORD: admin
        # Uncomment the line below if you want to specify JDBC parameters. The parameter below is just an example, and it shouldn't be used in production without knowledge. It is highly recommended that you read the MySQL JDBC driver documentation in order to use it.
        #JDBC_PARAMS: "connectTimeout=30000"
      ports:
        - 8080:8080
        - 9990:9990

