version: "3.8"

networks:
  local:
    name: localhost
    external: true

volumes:
  keycloak_data:
    name: keycloak-data
    driver: local

services:
  keycloak:
    container_name: keycloak-server
    image: quay.io/keycloak/keycloak:10.0.2
    command: ["-b", "0.0.0.0", "-bmanagement", "0.0.0.0"]
    volumes:
      - keycloak_data:/opt/jboss/keycloak
    environment:
      PROXY_ADDRESS_FORWARDING: "true"
      DB_VENDOR: POSTGRES
      DB_ADDR: 172.18.0.2
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_SCHEMA: public
      DB_PASSWORD: keycloak
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      #Uncomment the line below if you want to specify JDBC parameters. The parameter below is just an example, and it shouldn't be used in production without knowledge. It is highly recommended that you read the PostgreSQL JDBC driver documentation in order to use it.
      #JDBC_PARAMS: "ssl=true"
    ports:
      - 1002:8080
      - 1003:9990
      - 1004:8443
    networks:
      - local
