version: '3.8'

volumes:
  mysql_data:
      driver: local
  keycloak_data:
      driver: local

networks: 
    local:
      name: localhost
      driver: bridge

services:
  mysql_db:
      image: mysql:5.7
      volumes: 
       - mysql_data:/var/lib/mysql
      container_name: mysql-base
      command: ['mysqld', 
      '--character-set-server=utf8', 
      '--collation-server=utf8_unicode_ci', 
      '--bind-address=0.0.0.0', 
      '--default-authentication-plugin=mysql_native_password']
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: keycloak
        MYSQL_USER: keycloak
        MYSQL_PASSWORD: password
      networks:
        - local
  keycloak:
      image: quay.io/keycloak/keycloak:latest
      container_name: keycloak-server
      command: ["-b", "0.0.0.0", "-bmanagement", "0.0.0.0"]
      volumes:
        - keycloak_data:/opt/jboss/keycloak
      environment:
        PROXY_ADDRESS_FORWARDING: "true"
        DB_VENDOR: MYSQL
        DB_ADDR: mysql_db
        #DB_ADDR: 192.168.48.2
        DB_DATABASE: keycloak
        DB_USER: keycloak
        DB_PASSWORD: password     
        JDBC_PARAMS: "useSSL=false&characterEncoding=UTF-8"
      networks:
        - local
      ports:
        - 8080:8080
        - 9990:9990
      depends_on:
        - mysql_db
      links:
        - mysql_db