version: '3.8'

networks: 
  local:
    name: localhost
    external: true

volumes:
  postgres_data:
      name: postgres-repo
      driver: local

services:
  postgresql:
    container_name: postgresql-12
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: "password"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - local